name: Ci

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm ci
      - run: pnpm run build
      - run: pnpm test

      #- name: SonarCloud Scan
      #uses: sonarsource/sonarcloud-github-action@master
      #env:
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
